---
title: "Notebook flipthroughs, Hockney and learning how to make a statue"
author: "Raphaële Slimane"
date: 2025/09/13
description: " - "
image: ""
categories: 
  - blogging
execute: 
  echo: true
  message: false
  warning: false
  eval: false
format:
  html:
    code-fold: true
lightbox: 
  match: auto
  desc-position: right
  loop: true
---

## Art-related things that sparked joy in me - September 2

1. Why are we so fascinated by notebook flipthroughs? Like some of you, I’m an absolute fan of artistic notebook flipthrough videos : I’ll watch almost any kind - off the top of my head, Eleanor Doughty’s are favorites, for instance this one, or that one. The New Yorker once called this passion a “delightful form of snooping”, while writing about the Sketchbook Project. (This giant project began by giving blank Moleskines to people for a small fee and archiving whatever came back. In the end, there were thousands of notebooks from all sorts of people, that you could go and browse at the Brooklyn Art Library - the archives are now in transit to several museums.)
Here, I’m not talking about why having a sketchbook matters. I’m talking about why I love watching a video of the pages turning in a finished sketchbook. For me, it is energizing in the sense that you see individual pieces that form the flow of artistic life (a drawing of a building, or your little nephew’s feet) into a whole, an enclosed project that has a beginning, a middle, and an end. And as in all well-written stories, what makes a sketchbook flipthrough memorable is that there is variety: the good, the bad, and the ugly. Self-editing your own sketchbook too much might even do you a disservice. On that note, my mum used to say that the best part of my watercolor paintings was the blank paper next to the actual painting where I tested my colours. There’s beauty in seeing a sketchbook through to the end; a sense of awe at the artist’s consistency. September is a month of beginnings - usually a month when you start a sketchbook with a whole new academic year ahead of you (whether you’re a student or not), the crisp blank paper full of promises. Now, why not take an old sketchbook, finish it, and flip through it? Because, why the heck not.

2. Exhibition: I went to David Hockney’s exhibition (Hockney 25) in Paris two weeks ago and saw multiple echoes of van Gogh’s work. There was a room in the exhibition dedicated to Hockney’s work on moons (the moon room). Funnily enough, just as van Gogh tried to paint at night (arguing that even if he couldn’t see the colors on his palette, he could see the real scene in front of him), David Hockney resolved the quandary of painting outdoors at night by using the inherent lighting of the iPad.

3. Learning about how we make statues: A little while ago, I went drawing at the Musée Bourdelle in Paris with a friend. It has a garden full of sculptures made by Bourdelle, where you can sketch under the trees and walk along the green path that takes you from one gigantic statue to the next. I ended up watching a video on the process of making a bronze statue : I had no idea it was this complex ! I couldn’t find the video shown at the museum, but the Rodin Museum has a detailed description online.

4. I read the children’s book Les Vermeilles by Camille Jourdy. It is an enchanting tale about a girl who loses herself in the forest and meets all sorts of strange animals and people (for instance, the tiny queen and king on minuscule horses), echoing Spirited Away. The depiction of the forest, full of dots, reminded me of David Hockney’s paintings of Normandy although the color palettes are different: Hockney uses more vibrant greens, while Camille Jourdy works with pastel greens.

5. I re-read Austin Kleon’s Keep Going this week. I love this author - he is one of the best “artistic self-help” authors I know, and I mean that in the best possible way. Brace yourself for my favourite quotes: “Leonardo da Vinci made “to-learn” lists. He’d get up in the morning and write down everything he wanted to learn that day”. I’d take that any day over the endless to-do list at the start of the school year. The second one is about creative practice and money: “The minute anybody shows any talent for anything we suggest they turn it into a profession.[...] We used to have hobbies; now we have “side hustles”. And now, for something completely different : “I ignore every “35 under 35” list published.[...] I only want to read the “8 over 80” list””. Finally, that last bit is essentially the reason I am making this newsletter in the first place : “If art begins where we point our attention, a life is made out of paying attention to what we pay attention to”.