---
title: "5 art-related things that sparked something in me this week"
author: "Raphaële Slimane"
date: 2025/09/21
description: On lists as forms of art, taking a detour through Japanese aesthetics
categories: 
  - blogging
execute: 
  echo: true
  message: false
  warning: false
  eval: false
format:
  html:
    code-fold: true
lightbox: 
  match: auto
  desc-position: right
  loop: true
---


*In honor of my parents going to Japan, today’s list is made up of Japanese art-related things (except the first one).*


[Link to the post on my substack](https://raphaeleart.substack.com/p/5-art-related-things-that-sparked-052)

1. I’ve been reading a lot about lists lately. Lists can be forms of art. In the preface to [*Lists of Note*](https://www.goodreads.com/book/show/23123095-lists-of-note), [Shaun Usher](https://shaunusher.com/), who describes himself as a professional nerd, explains why we absolutely adore lists as human beings. He gives three reasons: *“life is chaotic”*; *“everyone is a critic”* (ranking things is addictive, I count myself in that category while writing this); and finally *“time is precious”* (making lists saves us time, so we have more time for hobbies and, of course, to make more lists). The book comprises many lists, some of which are terrifying or hilarious (like the list of temporary golf rules sent to club members while bombs were being dropped on the course in 1940, Richmond, England: *“during gunfire or while bombs are falling, players may take cover without penalty for ceasing play”*), some are wittily written ([list of rules for not flirting](https://en.wikipedia.org/wiki/Anti-Flirt_Club), distributed by the Anti-Flirt Club, an organization of women in the 1920s), and some are surprisingly accurate ([a wish list of things to be achieved by science made in 1662](https://royalsociety.org/blog/2010/08/what-scientists-want-boyle-list/) - many of which have since come true).  I also remembered stumbling upon a [self-help psychology book](https://www.fnac.com/a5920354/Dominique-Loreau-L-art-des-listes) about lists at the library a few years back. Most were the typical kinds of lists meant to help with life (your classic run-of-the-mill to-do lists), but what I loved were the weirder ones: like someone’s favorite lost lists.  For instance, one person lost a list made in Mexico, in front of La Casa Azul - where Frida Kahlo lived - containing the names of all the cats that had lived there, as told by the gardener (mysteriously lost on a bus). Art comes from all sorts of places - but for me, those places are often recorded in the Notes app on my phone. I wholeheartedly agree with the idea that “[the most interesting thing on someone’s phone is in their notes app](https://hannahconnolly.substack.com/),” as said by [Hannah Connolly](https://open.substack.com/users/2533229-hannah-connolly?utm_source=mentions).  In that spirit, go and make a weird list today ! 


2. **Animation**: last month, I had the opportunity to see [*Little Amélie, or the Character of Rain*](https://www.imdb.com/fr/title/tt29313285/?reasonForLanguagePrompt=browser_header_mismatch) in a small cinema in the village in the Alps where I was staying.  
Halfway through the film, I was completely charmed by: the multitude of colorful plants in the garden; Amélie’s discovery of white chocolate; the little radio that the Japanese nanny, Nishio-san, always carries with her to do her gymnastics; the way Amélie bottles all the sounds and impressions of the seaside for her nanny in a glass jar; the intricate construction of the lantern for the river ceremony; the making of spinning tops ([*goma*](https://www.epfl.ch/campus/associations/polyjapan/amelie-et-la-metaphysique-des-tubes/)) that make the child dizzy; and the reading of the *Book of Monsters* (*yōkai*).  
The style kept reminding me of something. It was only at the end that I noticed the name [Lucrèce Andreae](https://fr.wikipedia.org/wiki/Lucr%C3%A8ce_Andreae), credited for the storyboard. She is an incredibly talented artist, known for the short film [*Pépé le morse*](https://fr.wikipedia.org/wiki/P%C3%A9p%C3%A9_le_morse) (about grief over a grandfather’s death) and the graphic novel [*Flipette et Vénère*](https://www.editions-delcourt.fr/bd/series/serie-flipette-et-venere/album-flipette-et-venere).  
There are echoes in color and form across all three pieces: Amélie’s wide eyes as she looks at the garden resemble the child’s oversized eyes as he stares across the dunes at his grandfather’s “ghost”; the purplish tones of Amélie’s skin underwater mirror Vénère’s skin color in the graphic novel.  



3. This year, I discovered [*Tsukimi*](https://podcasts.apple.com/fr/podcast/tsukimi-le-podcast-pour-les-amoureux-du-japon/id1645323765), a podcast created by [Mathilda Motte](https://www.editionsdelamartiniere.fr/auteurs/mathilda-gourlez-de-la-motte/). I especially focused on the archived episodes that explore the stories and notable features of the traditional Japanese calendar ([*Kyûreki*](https://www.actes-sud-jeunesse.fr/9782330212384-l-emmanuelle-grundmann-gilberte-niamh-bourget-72-saisons-au-japon.htm)), month by month. There are 72 microseasons in a year. As I publish this post, the current microseason is [*swallows depart*](https://www.kyotoresearchinstitute.com/journal/microseason-swallows-depart?rq=swallows). Last week, [*wagtails sing*](https://www.kyotoresearchinstitute.com/journal/microseason-wagtail-sing) was in season, and next week, [*thunder’s voice quiets*](https://www.kyotoresearchinstitute.com/journal/microseason-thunders-voice-quiets) will follow. In September, the podcast invites us to observe: the leaves turning khaki green, dried sunflowers drooping, and the nostalgic feeling of summer’s end ([*nagori*](https://www.pol-editeur.com/index.php?spec=livre&ISBN=978-2-8180-4661-6)).  




4. **Radio interview**: [Ryoko Sekiguchi](https://fr.wikipedia.org/wiki/Ry%C5%8Dko_Sekiguchi) is a talented author and translator. In an [old interview](https://www.radiofrance.fr/franceinter/podcasts/remede-a-la-melancolie/ryoko-sekiguchi-il-est-possible-d-inviter-les-defunts-a-diner-4505540), she explains that writing can sometimes be a lonely endeavor. I remember she mentions three poetic ways to ease that weight:1) She would go out and eat at countertops in restaurants - not just any table, not on a patio, but at the old-fashioned, cafeteria-style counter where you’re never really eating alone. 2) While writing, she would also cook something very slowly, like a stew - the sounds and smells of cooking creating a presence. 3) She would buy lots of flowers to fill her apartment - thanks to all the money she had saved during the pandemic.  




5. **Book**: [*Tsubaki Stationery Store*, Ito Ogawa](https://www.babelio.com/livres/Ogawa-La-papeterie-Tsubaki/1050671). In this book, the main character returns to her hometown to work as a public scribe, in the shop her grandmother left her. The story is seemingly simple, but it’s filled with beautifully detailed artistic processes.  The character always takes the time to create - with her own hands - the most beautiful solution to each request. It’s funny because, in the book, she mentions feeling guilty when looking at her fountain pens, which she never cleans properly - unlike her grandmother, who always did. And now, this book gives me that *exact* same feeling whenever I think about my own fountain pen, which I also never clean properly (I know I should).  


Thank you for reading this totally free, human-made newsletter that focuses on art-related things I found interesting - and that hopefully you do too.  
